# Generated by Django 3.0.3 on 2020-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('item_id', models.TextField(max_length=200, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('clas', models.TextField(max_length=100, verbose_name='类别')),
                ('htmurl', models.CharField(max_length=100, verbose_name='网页地址')),
                ('m3u8url', models.TextField(max_length=200, verbose_name='视频地址')),
                ('upLoadTime', models.CharField(max_length=50, verbose_name='上传时间')),
                ('states', models.CharField(max_length=50, verbose_name='描述')),
                ('img', models.CharField(max_length=127, verbose_name='图片')),
            ],
            options={
                'db_table': 'movie_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('city_id', models.CharField(max_length=100, verbose_name='城市编号')),
                ('gardenId', models.CharField(max_length=100, verbose_name='小区编号')),
                ('gardenName', models.CharField(max_length=100, verbose_name='')),
                ('roomId', models.CharField(max_length=100, verbose_name='')),
                ('house_id', models.CharField(max_length=100, verbose_name='')),
                ('house_type', models.CharField(max_length=100, verbose_name='')),
                ('bildingname', models.CharField(max_length=100, verbose_name='')),
                ('volume_ratio', models.CharField(max_length=100, verbose_name='')),
                ('region', models.CharField(max_length=100, verbose_name='')),
                ('greening_rate', models.CharField(max_length=100, verbose_name='')),
                ('reference_price', models.CharField(max_length=100, verbose_name='')),
                ('totle_house', models.CharField(max_length=100, verbose_name='')),
                ('decoration_situation', models.CharField(max_length=100, verbose_name='')),
                ('parking_place', models.CharField(max_length=100, verbose_name='')),
                ('area', models.CharField(max_length=100, verbose_name='')),
                ('property_company', models.CharField(max_length=100, verbose_name='')),
                ('property_fee', models.CharField(max_length=100, verbose_name='')),
                ('developers', models.CharField(max_length=100, verbose_name='')),
                ('ts', models.CharField(max_length=100, verbose_name='')),
                ('price_sum', models.CharField(max_length=100, verbose_name='')),
                ('price_time', models.CharField(max_length=100, verbose_name='')),
                ('use', models.CharField(max_length=100, verbose_name='')),
                ('property_right', models.CharField(max_length=100, verbose_name='')),
                ('opening_time', models.CharField(max_length=100, verbose_name='')),
                ('delivery_time', models.CharField(max_length=100, verbose_name='')),
                ('bh', models.CharField(max_length=100, verbose_name='')),
                ('address', models.CharField(max_length=100, verbose_name='')),
                ('types', models.CharField(max_length=100, verbose_name='')),
                ('latitude', models.CharField(max_length=100, verbose_name='')),
                ('longitude', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'db_table': 'dhouse',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单编号')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=20, verbose_name='链接地址')),
                ('order', models.CharField(max_length=20, verbose_name='排序')),
            ],
            options={
                'verbose_name': '浏览菜单信息',
                'verbose_name_plural': '菜单信息管理',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MyDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.TextField(max_length=100, verbose_name='文档编号')),
                ('docName', models.TextField(max_length=100, verbose_name='文档名称')),
                ('docContext', models.TextField(max_length=100, verbose_name='文档简介')),
                ('docLink', models.TextField(max_length=100, verbose_name='网络链接')),
                ('docLocalurl', models.TextField(max_length=100, verbose_name='本地地址')),
                ('docClas', models.TextField(max_length=100, verbose_name='分裂')),
                ('docState', models.TextField(max_length=100, verbose_name='状态')),
                ('docOrder', models.TextField(max_length=100, verbose_name='排序')),
            ],
            options={
                'verbose_name': '文档管理',
                'db_table': 'myDoc',
            },
        ),
        migrations.CreateModel(
            name='Spider_p',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='爬虫名称')),
                ('spider_dir', models.CharField(max_length=100, verbose_name='文件路径')),
                ('context', models.TextField(max_length=500, verbose_name='描述')),
                ('order_p', models.IntegerField(verbose_name='优先级')),
            ],
            options={
                'verbose_name_plural': '爬虫管理',
                'db_table': 'spider_p',
            },
        ),
        migrations.CreateModel(
            name='Spiderpitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField(max_length=255, verbose_name='标题')),
                ('longitude', models.TextField(max_length=255, verbose_name='标题')),
                ('latitude', models.TextField(max_length=255, verbose_name='标题')),
                ('city_name', models.TextField(max_length=255, verbose_name='标题')),
                ('gardenId', models.TextField(max_length=255, verbose_name='标题')),
                ('gardenName', models.TextField(max_length=255, verbose_name='标题')),
                ('roomId', models.TextField(max_length=255, verbose_name='标题')),
                ('city_id', models.TextField(max_length=255, verbose_name='标题')),
                ('house_id', models.TextField(max_length=255, verbose_name='标题')),
                ('volume_ratio', models.TextField(max_length=255, verbose_name='标题')),
                ('region', models.TextField(max_length=255, verbose_name='标题')),
                ('greening_rate', models.TextField(max_length=255, verbose_name='标题')),
                ('reference_price', models.TextField(max_length=255, verbose_name='标题')),
                ('totle_house', models.TextField(max_length=255, verbose_name='标题')),
                ('decoration_situation', models.TextField(max_length=255, verbose_name='标题')),
                ('parking_place', models.TextField(max_length=255, verbose_name='标题')),
                ('area', models.TextField(max_length=255, verbose_name='标题')),
                ('property_company', models.TextField(max_length=255, verbose_name='标题')),
                ('property_fee', models.TextField(max_length=255, verbose_name='标题')),
                ('developers', models.TextField(max_length=255, verbose_name='标题')),
                ('ts', models.TextField(max_length=255, verbose_name='标题')),
                ('price_sum', models.TextField(max_length=255, verbose_name='标题')),
                ('price_time', models.TextField(max_length=255, verbose_name='标题')),
                ('use', models.TextField(max_length=255, verbose_name='标题')),
                ('property_right', models.TextField(max_length=255, verbose_name='标题')),
                ('opening_time', models.TextField(max_length=255, verbose_name='标题')),
                ('delivery_time', models.TextField(max_length=255, verbose_name='标题')),
                ('bh', models.TextField(max_length=255, verbose_name='标题')),
                ('address', models.TextField(max_length=255, verbose_name='标题')),
                ('url', models.TextField(max_length=255, verbose_name='标题')),
                ('house_type', models.TextField(max_length=255, verbose_name='标题')),
            ],
            options={
                'db_table': 'spiderpitem_',
            },
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('classid', models.CharField(max_length=8, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Sv',
            fields=[
                ('item_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='m3u8地址')),
                ('url', models.TextField(max_length=255, verbose_name='m3u8地址')),
                ('name', models.TextField(max_length=255, verbose_name='标题')),
                ('time', models.TimeField(verbose_name='创建时间')),
                ('img', models.TextField(max_length=150, verbose_name='图片地址')),
            ],
            options={
                'db_table': 'sswgvideo_',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
